AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  solaredge-powermonitoring

  Sample SAM Template for solaredge-powermonitoring

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  SolaredgePowerMonitorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: solaredge-pm/
      Role: arn:aws:iam::464277983547:role/LambdaSESRole
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)

Outputs:
  SolaredgePowerMonitorFunction:
    Description: "SolarEdge Power Monitor Lambda Function ARN"
    Value: !GetAtt SolaredgePowerMonitorFunction.Arn

